### ISSUE TITLE
C.36.3 and AY.2 not found

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangoLEARN#21]
I reran the analysis for all our samples and these lineages are assigned, but miss a description

Best,
Anke

**Comment by AKWB** [comment]
I meant C.36.3.1...

**Comment by rmcolq** [comment]
I'm glad that you now have lineage assignments. I'm going to close this as an old issue - if you still have problems feel free to open a software issue on https://github.com/cov-lineages/pangolin/issues (this pangoLEARN issue list is not checked often because the repository only contains the data models)
